name: auto-mail-front

services:
  app:
    container_name: auto-mail-front-prod
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://98.93.234.2:8000/api/v1}
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - auto-mail-front-network-prod

networks:
  auto-mail-front-network-prod:
    driver: bridge

