name: auto-mail-front

services:
  app:
    container_name: auto-mail-front
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ../app:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api/v1
    restart: unless-stopped
    networks:
      - auto-mail-front-network

networks:
  auto-mail-front-network:
    driver: bridge

